version: 2

sources: 
  - name: raw
    schema: gz_raw_data
    description: greenzweez raw data source
    tables:
      - name: sales
        freshness: 
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"

        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each orders_id
        
        columns:
          - name: products_id
            description: the identifier of the product

          - name: date_date
            description: the date of purchase

          - name: orders_id
            description: the identifier of the order

          - name: revenue
            description: the revenue price

          - name: quantity
            description: the quantity of the same requested product

        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
          - not_null:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        description: products of greenweez / we have one row per products_id and its purchase_price
        columns:
          - name: products_id
            description: the identifier of the product
            tests:
              - unique
              - not_null

          - name: purchase_price
            description: the purchase price

      - name: ship
        identifier: raw_gz_ship
        description: shipping logs of greenweez / we have one row per orders_id and its operational costs
        columns:
          - name: orders_id
            description: the identifier of the order
            tests:
              - unique
              - not_null

          - name: shipping_fee
            description: shipping cost paid by the customer

          - name: log_cost
            description: operational cost

          - name: ship_cost
            description: shipping cost paid by the company
            
      - name: adwords
        identifier: raw_gz_adwords
      
      - name: bing
        identifier: raw_gz_bing
      
      - name: facebook
        identifier: raw_gz_facebook

      - name: criteo
        identifier: raw_gz_criteo